### PR TITLE
Add toml as a run dependency and update pylint and pytest versions

### PR DESCRIPTION
**Pull request by n-elie**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

This PR adds `toml` as a run dependency. It's needed since `pytest-pylint` v0.15.1.
Also update pytest and pylint minimum versions.

### CODE REVIEW

**Comment by gatesn** [comment]
I think you also want to update the pytest dependency: https://github.com/carsongee/pytest-pylint/blob/master/setup.py#L23

**Comment by n-elie** [comment]
> I think you also want to update the pytest dependency: https://github.com/carsongee/pytest-pylint/blob/master/setup.py#L23

Done

**Comment by n-elie** [comment]
@conda-forge-admin, please rerender

**Comment by n-elie** [comment]
Is there anything missing?

**Review by holgern — APPROVED** [review]

**Pull request merged**
